image_width: 640
image_height: 480
camera_name: head_camera
camera_matrix:
  rows: 3
  cols: 3
  data: [579.51485,   0.     , 312.69347,
           0.     , 577.66079, 253.78003,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.059291, -0.159216, 0.002227, -0.002481, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [580.43988,   0.     , 310.68298,   0.     ,
           0.     , 580.00061, 254.03032,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
